apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspector
  namespace: NOME_DO_NAMESPACE
spec:
  containers:
  - image: srlinuxme/pvc-inspector:jammy
    name: pvc-inspector
    command: ["tail"]
    args: ["-f", "/dev/null"]
    volumeMounts:
    - mountPath: /pvc
      name: pvc-mount
  volumes:
  - name: pvc-mount
    persistentVolumeClaim:
      claimName: YOUR_CLAIM_NAME_HERE
